### ISSUE TITLE
test failures in latest release, all pythons

### ISSUE THREAD

**Issue by idella** [ContinuumIO/datashape#78]
```python
datashape.tests.test_user.test_tuples_can_be_records_too ... ok
datashape.tests.test_user.test_datetimes ... ok
datashape.tests.test_user.test_numpy ... ok
datashape.tests.test_user.test_issubschema ... ok
datashape.tests.test_user.test_integration ... ok
test_cat_dshapes (datashape.tests.test_util.TestDataShapeUtil) ... ok
test_cat_dshapes_errors (datashape.tests.test_util.TestDataShapeUtil) ... ok
test_has_ellipsis (datashape.tests.test_util.TestDataShapeUtil) ... ok
test_has_var_dim (datashape.tests.test_util.TestDataShapeUtil) ... ok

======================================================================
ERROR: test_coerce_traits (datashape.tests.test_coercion.TestCoercion)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/gen2/TmpDir/portage/dev-python/datashape-0.3.0/work/datashape-0.3.0-python3_4/lib/datashape/tests/test_coercion.py", line 75, in test_coerce_traits
    '10 * X * float32')
  File "/mnt/gen2/TmpDir/portage/dev-python/datashape-0.3.0/work/datashape-0.3.0-python3_4/lib/datashape/util.py", line 34, in dshapes
    return [dshape(arg) for arg in args]
  File "/mnt/gen2/TmpDir/portage/dev-python/datashape-0.3.0/work/datashape-0.3.0-python3_4/lib/datashape/util.py", line 34, in <listcomp>
    return [dshape(arg) for arg in args]
  File "/mnt/gen2/TmpDir/portage/dev-python/datashape-0.3.0/work/datashape-0.3.0-python3_4/lib/datashape/util.py", line 49, in dshape
    ds = parser.parse(o, type_symbol_table.sym)
  File "/mnt/gen2/TmpDir/portage/dev-python/datashape-0.3.0/work/datashape-0.3.0-python3_4/lib/datashape/parser.py", line 582, in parse
    dsp.raise_error('Unexpected token in datashape')
  File "/mnt/gen2/TmpDir/portage/dev-python/datashape-0.3.0/work/datashape-0.3.0-python3_4/lib/datashape/parser.py", line 57, in raise_error
    self.ds_str, errmsg)
nose.proxy.DataShapeSyntaxError: 

  File <nofile>, line 1
    10 * X * A : floating
               ^

DataShapeSyntaxError: Unexpected token in datashape

-------------------- >> begin captured stdout << ---------------------


  File <nofile>, line 1
    10 * X * A : floating
               ^

DataShapeSyntaxError: Unexpected token in datashape


--------------------- >> end captured stdout << ----------------------

======================================================================
ERROR: test_constraints_error (datashape.tests.test_creation.TestDataShapeCreation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/gen2/TmpDir/portage/dev-python/datashape-0.3.0/work/datashape-0.3.0-python3_4/lib/datashape/tests/test_creation.py", line 62, in test_constraints_error
    'A : integral * B : numeric')
  File "/usr/lib64/python3.4/unittest/case.py", line 701, in assertRaises
    return context.handle('assertRaises', callableObj, args, kwargs)
  File "/usr/lib64/python3.4/unittest/case.py", line 161, in handle
    callable_obj(*args, **kwargs)
  File "/mnt/gen2/TmpDir/portage/dev-python/datashape-0.3.0/work/datashape-0.3.0-python3_4/lib/datashape/util.py", line 49, in dshape
    ds = parser.parse(o, type_symbol_table.sym)
  File "/mnt/gen2/TmpDir/portage/dev-python/datashape-0.3.0/work/datashape-0.3.0-python3_4/lib/datashape/parser.py", line 582, in parse
    dsp.raise_error('Unexpected token in datashape')
  File "/mnt/gen2/TmpDir/portage/dev-python/datashape-0.3.0/work/datashape-0.3.0-python3_4/lib/datashape/parser.py", line 57, in raise_error
    self.ds_str, errmsg)
nose.proxy.DataShapeSyntaxError: 

  File <nofile>, line 1
    A : integral * B : numeric
      ^

DataShapeSyntaxError: Unexpected token in datashape

-------------------- >> begin captured stdout << ---------------------


  File <nofile>, line 1
    A : integral * B : numeric
      ^

DataShapeSyntaxError: Unexpected token in datashape


--------------------- >> end captured stdout << ----------------------

======================================================================
ERROR: test_type_decl (datashape.tests.test_creation.TestDataShapeCreation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/gen2/TmpDir/portage/dev-python/datashape-0.3.0/work/datashape-0.3.0-python3_4/lib/datashape/tests/test_creation.py", line 70, in test_type_decl
    self.assertRaises(error.DataShapeTypeError, dshape, 'type X T = 3, T')
  File "/usr/lib64/python3.4/unittest/case.py", line 701, in assertRaises
    return context.handle('assertRaises', callableObj, args, kwargs)
  File "/usr/lib64/python3.4/unittest/case.py", line 161, in handle
    callable_obj(*args, **kwargs)
  File "/mnt/gen2/TmpDir/portage/dev-python/datashape-0.3.0/work/datashape-0.3.0-python3_4/lib/datashape/util.py", line 49, in dshape
    ds = parser.parse(o, type_symbol_table.sym)
  File "/mnt/gen2/TmpDir/portage/dev-python/datashape-0.3.0/work/datashape-0.3.0-python3_4/lib/datashape/parser.py", line 578, in parse
    dsp.raise_error('Invalid datashape')
  File "/mnt/gen2/TmpDir/portage/dev-python/datashape-0.3.0/work/datashape-0.3.0-python3_4/lib/datashape/parser.py", line 57, in raise_error
    self.ds_str, errmsg)
nose.proxy.DataShapeSyntaxError: 

  File <nofile>, line 1
    type X T = 3, T
    ^

DataShapeSyntaxError: Invalid datashape

-------------------- >> begin captured stdout << ---------------------


  File <nofile>, line 1
    type X T = 3, T
    ^

DataShapeSyntaxError: Invalid datashape


--------------------- >> end captured stdout << ----------------------

======================================================================
ERROR: test_best_match (datashape.tests.test_overloading.TestOverloading)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/gen2/TmpDir/portage/dev-python/datashape-0.3.0/work/datashape-0.3.0-python3_4/lib/datashape/tests/test_overloading.py", line 18, in test_best_match
    match = best_match(f, coretypes.Tuple([d1, d2]))
NameError: name 'best_match' is not defined

======================================================================
FAIL: test_coerce_constrained_typevars (datashape.tests.test_coercion.TestCoercion)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/gen2/TmpDir/portage/dev-python/datashape-0.3.0/work/datashape-0.3.0-python3_4/lib/datashape/tests/test_coercion.py", line 55, in test_coerce_constrained_typevars
    self.assertGreater(coercion_cost(a, b), coercion_cost(a, c))
  File "/mnt/gen2/TmpDir/portage/dev-python/datashape-0.3.0/work/datashape-0.3.0-python3_4/lib/datashape/tests/common.py", line 15, in assertGreater
    self.assertTrue(a > b, msg or "%s is not greater than %s" % (a, b))
AssertionError: False is not true : 1 is not greater than 1

======================================================================
FAIL: test_coerce_src_ellipsis (datashape.tests.test_coercion.TestCoercion)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/gen2/TmpDir/portage/dev-python/datashape-0.3.0/work/datashape-0.3.0-python3_4/lib/datashape/tests/test_coercion.py", line 87, in test_coerce_src_ellipsis
    self.assertGreater(coercion_cost(a, b), coercion_cost(a, c))
  File "/mnt/gen2/TmpDir/portage/dev-python/datashape-0.3.0/work/datashape-0.3.0-python3_4/lib/datashape/tests/common.py", line 15, in assertGreater
    self.assertTrue(a > b, msg or "%s is not greater than %s" % (a, b))
AssertionError: False is not true : 1 is not greater than inf

======================================================================
FAIL: test_coerce_typevars (datashape.tests.test_coercion.TestCoercion)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/gen2/TmpDir/portage/dev-python/datashape-0.3.0/work/datashape-0.3.0-python3_4/lib/datashape/tests/test_coercion.py", line 49, in test_coerce_typevars
    self.assertGreater(coercion_cost(a, b), coercion_cost(a, c))
  File "/mnt/gen2/TmpDir/portage/dev-python/datashape-0.3.0/work/datashape-0.3.0-python3_4/lib/datashape/tests/common.py", line 15, in assertGreater
    self.assertTrue(a > b, msg or "%s is not greater than %s" % (a, b))
AssertionError: False is not true : 1 is not greater than 1

======================================================================
FAIL: datashape.tests.test_discovery.test_time_string
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/mnt/gen2/TmpDir/portage/dev-python/datashape-0.3.0/work/datashape-0.3.0-python3_4/lib/datashape/tests/test_discovery.py", line 81, in test_time_string
    assert discover('12:00:01') == time_
AssertionError

----------------------------------------------------------------------
Ran 133 tests in 0.506s

FAILED (errors=4, failures=4)
```

ply; Installed versions:  3.4
numpy; Installed versions:  0.4
multipledispatch; Installed versions:  0.4.4

uder pythons 2.7 3.3 3.4. Can you replicate? Do you require anything further?

**Comment by cpcloud** [comment]
There's a distinction between skipping a test and `xfail`ing a test. We skip on things such as platform dependent code. An obvious example is something like shelling out on linux using `bash`. This isn't something that can ever be depended on existing in a Windows environment and we acknowledge this by skipping the test on Windows. When a test probably should pass, but the code that the test exercises isn't implemented, `xfail` is a nice choice. `pytest` will even let you know when tests that are `xfail`ing start to pass. Unittest doesn't currently have this capability out of the box AFAIK.

**Comment by bnavigator** [comment]
```
[    3s] =================================== FAILURES ===================================
[    3s] __________________________ test_arbitrary_string[s4] ___________________________
[    3s] 
[    3s] s = MarkDecorator(mark=Mark(name='xfail', args=('{"/a/b/0/c\x0b/d": int8}',), kwargs={'raises': <class 'datashape.error.DataShapeSyntaxError'>}))
[    3s] 
[    3s]     @pytest.mark.parametrize('s',
[    3s]                              ['{"./abc": int64}',
[    3s]                               '{"./a b c": float64}',
[    3s]                               '{"./a b\tc": string}',
[    3s]                               '{"./a/[0 1 2]/b/\\n": float32}',
[    3s]                               pytest.mark.xfail('{"/a/b/0/c\v/d": int8}',
[    3s]                                                 raises=DataShapeSyntaxError),
[    3s]                               pytest.mark.xfail('{"/a/b/0/c\n/d": int8}',
[    3s]                                                 raises=DataShapeSyntaxError),
[    3s]                               pytest.mark.xfail('{"/a/b/0/c\r/d": int8}',
[    3s]                                                 raises=DataShapeSyntaxError)])
[    3s]     def test_arbitrary_string(s):
[    3s] >       ds = dshape(s)
[    3s] 
[    3s] datashape/tests/test_str.py:69: 
[    3s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[    3s] 
[    3s] o = MarkDecorator(mark=Mark(name='xfail', args=('{"/a/b/0/c\x0b/d": int8}',), kwargs={'raises': <class 'datashape.error.DataShapeSyntaxError'>}))
[    3s] 
[    3s]     def dshape(o):
[    3s]         """
[    3s]         Parse a datashape. For a thorough description see
[    3s]         http://blaze.pydata.org/docs/datashape.html
[    3s]     
[    3s]         >>> ds = dshape('2 * int32')
[    3s]         >>> ds[1]
[    3s]         ctype("int32")
[    3s]         """
[    3s]         if isinstance(o, coretypes.DataShape):
[    3s]             return o
[    3s]         if isinstance(o, py2help._strtypes):
[    3s]             ds = parser.parse(o, type_symbol_table.sym)
[    3s]         elif isinstance(o, (coretypes.CType, coretypes.String,
[    3s]                             coretypes.Record, coretypes.JSON,
[    3s]                             coretypes.Date, coretypes.Time, coretypes.DateTime,
[    3s]                             coretypes.Unit)):
[    3s]             ds = coretypes.DataShape(o)
[    3s]         elif isinstance(o, coretypes.Mono):
[    3s]             ds = o
[    3s]         elif isinstance(o, (list, tuple)):
[    3s]             ds = coretypes.DataShape(*o)
[    3s]         else:
[    3s] >           raise TypeError('Cannot create dshape from object of type %s' % type(o))
[    3s] E           TypeError: Cannot create dshape from object of type <class '_pytest.mark.structures.MarkDecorator'>
[    3s] 
[    3s] datashape/util/__init__.py:54: TypeError
```

For the record, marking xfail a parametrized test works differently nowadays.
https://docs.pytest.org/en/stable/skipping.html#skip-xfail-with-parametrize
